DROP DATABASE secure;
DROP DATABASE secure_0;
DROP DATABASE secure_1;

DROP DATABASE media_0;
DROP DATABASE media_1;

DROP DATABASE finance_0;
DROP DATABASE finance_1;

DROP DATABASE marketing_0;
DROP DATABASE marketing_1;

DROP DATABASE member_0;
DROP DATABASE member_1;

DROP DATABASE portal_0;
DROP DATABASE portal_1;

DROP DATABASE business_0;
DROP DATABASE business_1;

DROP DATABASE base;
DROP DATABASE base_0;
DROP DATABASE base_1;

DROP DATABASE dict;