package com.blue.base.repository.mapper;

import com.blue.base.repository.entity.DictType;
import com.blue.base.repository.entity.DictTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    long countByExample(DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int deleteByExample(DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int insert(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int insertSelective(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    List<DictType> selectByExample(DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    DictType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictType record, @Param("example") DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictType record, @Param("example") DictTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictType record);
}