package com.blue.base.repository.mapper;

import com.blue.base.repository.entity.Dict;
import com.blue.base.repository.entity.DictExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    long countByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int deleteByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int insert(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int insertSelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    List<Dict> selectByExample(DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    Dict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dict record, @Param("example") DictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dict record);
}