server:
  address: 127.0.0.1
  port: 41000
  netty:
    connection-timeout: 6s
    h2c-max-content-length: 0B
    initial-buffer-size: 128B
    max-chunk-size: 8KB
    max-initial-line-length: 4KB
    validate-headers: true
  http2:
    enabled: true
  error:
    path: /error
#  ssl:
#    client-auth: need
#    ciphers: [ ]
#    enabled-protocols: [ ]
#    key-alias:
#    key-password:
#    key-store:
#    key-store-password:
#    key-store-type:
#    key-store-provider:
#    trust-store:
#    trust-store-password:
#    trust-store-type:
#    trust-store-provider:
#    protocol: TLS


eureka:
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 60
    instance-id: ${server.address}:${spring.application.name}:${server.port}
    hostname: ${server.address}
  client:
    service-url:
      defaultZone: http://blue:LiuZhiyi20200805@101.43.192.155:3000/eureka/
    registry-fetch-interval-seconds: 60


identity:
  data-center: 0
  worker: 0
  service-name: blue-article
  boot-seconds: 1618790400
  buffer-power: 3
  padding-factor: 50
  padding-core-pool-size: 1
  padding-maximum-pool-size: 2
  keep-alive-seconds: 128
  padding-blocking-queue-size: 1024
  padding-scheduled: true
  padding-scheduled-core-pool-size: 2
  padding-scheduled-initial-delay-millis: 5000
  padding-scheduled-delay-millis: 15000


mongo:
  address-attrs:
    - address: 43.138.44.171
      port: 27017
  auth: true
  auth-base: admin
  user-name: blue
  password: LiuZhiyi20200805
  database: article
  retry-reads: false
  retry-writes: false
  application-name: blue-article
  uuid-representation: JAVA_LEGACY
  socket-connect-timeout-millis: 60000
  socket-read-timeout-millis: 60000
  socket-receive-buffer-size: 10000
  socket-send-buffer-size: 256
  cluster-connection-mode: SINGLE
  cluster-type: STANDALONE
  cluster-local-threshold-millis: 60000
  server-selection-timeout-millis: 60000
  pool-max-size: 12
  pool-min-size: 2
  pool-max-wait-time-millis: 60000
  pool-max-connection-lifeTime-millis: 60000
  pool-max-connection-idle-time-millis: 60000
  pool-maintenance-initial-delay-millis: 60000
  pool-maintenance-frequency-millis: 60000


es:
  es-nodes:
    - server:
        host: 127.0.0.1
        port: 9200
        schema: http
      bound-servers: [ ]
      name: blue-es
      version: 8.5.0
      roles: [ ]
      attributes: [ ]
  default-headers:
  path-prefix: /
  strict-deprecation-mode: false
  meta-header-enabled: false
  compression-enabled: false


cache:
  server-mode: SINGLE
  nodes: [ 172.20.20.2:6379,172.20.20.2:6380,172.20.20.3:6379,172.20.20.3:6380,172.20.20.4:6379,172.20.20.4:6380 ]
  address: 43.138.111.53:6379
  password: LiuZhiyi20200805
  max-redirects: 4
  min-idle: 4
  max-idle: 64
  max-total: 128
  max-wait-millis: 16
  auto-reconnect: true
  buffer-usage-ratio: 32.0
  cancel-commands-on-reconnect-failure: false
  ping-before-activate-connection: false
  request-queue-size: 64
  publish-on-scheduler: true
  tcp-no-delay: true
  connect-timeout: 10
  keep-alive: false
  suspend-reconnect-on-protocol-failure: false
  command-timeout: 4
  shutdown-timeout: 8
  shutdown-quiet-period: 4
  entry-ttl: 60


local-cache:
  size: 300
  expire-time: 120


executor:
  core-pool-size: 4
  maximum-pool-size: 8
  keep-alive-seconds: 64
  blocking-queue-capacity: 128
  thread-name-pre: blue-summer


message:
  message-location: classpath:i18n/message
  element-location: classpath:i18n/element





redisson:
  server-mode: SINGLE
  nodes: [ 172.20.20.2:6379,172.20.20.2:6380,172.20.20.3:6379,172.20.20.3:6380,172.20.20.4:6379,172.20.20.4:6380 ]
  address: 43.138.111.53:6379
  password: LiuZhiyi20200805
  scan-interval: 8000
  check-slots-coverage: false
  tcp-no-delay: true
  master-connection-minimum-idle-size: 2
  slave-connection-minimum-idle-size: 2
  master-connection-pool-size: 2
  slave-connection-pool-size: 2
  subscription-connection-minimum-idle-size: 2
  subscription-connection-pool-size: 2
  subscriptions-per-connection: 2
  subscription-mode: MASTER
  timeout: 60000
  connect-timeout: 60000
  idle-connection-timeout: 32000
  retry-attempts: 2
  retry-interval: 4000
  keep-alive: true
  dns-monitoring-interval: -1
  ping-connection-interval: 300000
  executor-core-pool-size: 4
  executor-maximum-pool-size: 8
  executor-keep-alive-seconds: 64
  executor-blocking-queue-capacity: 128
  max-tryLock-waiting-millis: 10000


rest:
  max-connections: 64
  worker-count: 64
  use-global-resources: false
  connect-timeout-millis: 7000
  use-tcp-no-delay: false
  protocols: [ HTTP11,H2,H2C ]
  response-timeout-millis: 3000
  read-timeout-millis: 3000
  write-timeout-millis: 3000
  max-byte-in-memory-size: 1048576


dubbo:
  registry:
    id: summer-registry
    client: curator
    protocol: zookeeper
    address: zookeeper://43.138.44.171
    port: 2181
    username: blue
    password: LiuZhiyi20200805
    file: /usr/env/log/dubbo/article/registry.properties
    check: false
    timeout: 60000
    simplified: false
#  metadata-report:
#    address: zookeeper://43.138.44.171
#    port: 2181
#    username: blue
#    password: LiuZhiyi20200805
#    timeout: 120000
#    default: true
#    check: false
  protocol:
    name: dubbo
    host: localhost
    port: 42000
    accesslog: /usr/env/log/dubbo/article/access.log
  provider:
    retries: 0
    timeout: 10000
    loadbalance: random
  consumer:
    retries: 0
    timeout: 10000
    loadbalance: random
    check: false


debug: false