server:
  address: 127.0.0.1
  port: 59000
  netty:
    connection-timeout: 6s
    h2c-max-content-length: 0B
    initial-buffer-size: 128B
    max-chunk-size: 8KB
    max-initial-line-length: 4KB
    validate-headers: true
  http2:
    enabled: true
  error:
    path: /error
#  ssl:
#    client-auth: need
#    ciphers: [ ]
#    enabled-protocols: [ ]
#    key-alias:
#    key-password:
#    key-store:
#    key-store-password:
#    key-store-type:
#    key-store-provider:
#    trust-store:
#    trust-store-password:
#    trust-store-type:
#    trust-store-provider:
#    protocol: TLS


eureka:
  instance:
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 60
    instance-id: ${server.address}:${spring.application.name}:${server.port}
    hostname: ${server.address}
  client:
    service-url:
      defaultZone: http://blue:LiuZhiyi20200805@101.43.192.155:3000/eureka/
    registry-fetch-interval-seconds: 60


data:
  sharding-databases:
    - url: jdbc:mysql://101.43.192.155:3306/article_0
      database-conf: useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: LiuZhiyi20200805
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 120000
      max-lifetime: 1800000
      max-pool-size: 4
      min-idle: 2
      idle-timeout: 5
      connection-test-query: SELECT 1 FROM DUAL
      is-read-only: false
      is-auto-commit: true

    - url: jdbc:mysql://43.138.44.171:3306/article_1
      database-conf: useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: LiuZhiyi20200805
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 120000
      max-lifetime: 1800000
      max-pool-size: 4
      min-idle: 2
      idle-timeout: 5
      connection-test-query: SELECT 1 FROM DUAL
      is-read-only: false
      is-auto-commit: true
  sharding-tables:
    - table-name: article
      sharding-column: id

    - table-name: link
      sharding-column: id

    - table-name: comment
      sharding-column: id

    - table-name: reply
      sharding-column: id
  sharding-table-size-per-database: 2
  data-center-to-database-mappings:
    - id: 0
      index: 0

    - id: 1
      index: 1
  worker-to-table-mappings:
    - id: 0
      index: 0

    - id: 1
      index: 1
  broadcast-tables: [ ]
  safe-row-bounds-enabled: false
  safe-result-handler-enabled: false
  map-underscore-to-camel-case: true
  aggressive-lazy-loading: false
  multiple-result-sets-enabled: false
  use-generated-keys: false
  use-column-label: true
  cache-enabled: false
  call-setters-on-nulls: false
  use-actual-param-name: false
  return-instance-for-empty-row: false
  shrink-whitespaces-in-sql: false
  nullable-on-for-each: false
  local-cache-scope: SESSION
  jdbc-type-for-null:
  default-statement-timeout: 30000
  default-fetch-size: 100
  default-result-set-type: DEFAULT
  default-executor-type: BATCH
  auto-mapping-behavior: FULL
  auto-mapping-unknown-column-behavior: FAILING
  lazy-loading-enabled: false
  mapper-location: classpath:mapper/*.xml
  props:
    sql.show: true
    sql.simple: false
    executor.size: 128
    max.connections.size.per.query: 2
    check.table.metadata.enabled: true
    query.with.cipher.column: false
    xa.transaction.manager.type: Atomikos
  debug-logging: true


identity:
  data-center: 0
  worker: 0
  service-name: blue-agreement
  boot-seconds: 1618790400
  buffer-power: 3
  padding-factor: 50
  padding-core-pool-size: 1
  padding-maximum-pool-size: 2
  keep-alive-seconds: 128
  padding-blocking-queue-size: 1024
  padding-scheduled: true
  padding-scheduled-core-pool-size: 2
  padding-scheduled-initial-delay-millis: 5000
  padding-scheduled-delay-millis: 15000


cache:
  server-mode: SINGLE
  nodes: [ 172.20.20.2:6379,172.20.20.2:6380,172.20.20.3:6379,172.20.20.3:6380,172.20.20.4:6379,172.20.20.4:6380 ]
  host: 43.138.111.53
  port: 6379
  password: LiuZhiyi20200805
  max-redirects: 4
  min-idle: 4
  max-idle: 64
  max-total: 128
  max-wait-millis: 16
  auto-reconnect: true
  buffer-usage-ratio: 32.0
  cancel-commands-on-reconnect-failure: false
  ping-before-activate-connection: false
  request-queue-size: 64
  publish-on-scheduler: true
  tcp-no-delay: true
  connect-timeout: 10
  keep-alive: false
  suspend-reconnect-on-protocol-failure: false
  command-timeout: 4
  shutdown-timeout: 8
  shutdown-quiet-period: 4
  entry-ttl: 60


local-cache:
  size: 300
  expire-time: 120


executor:
  core-pool-size: 4
  maximum-pool-size: 8
  keep-alive-seconds: 64
  blocking-queue-capacity: 128
  thread-name-pre: blue-summer


message:
  message-location: classpath:i18n/message
  element-location: classpath:i18n/element





redisson:
  server-mode: SINGLE
  nodes: [ 172.20.20.2:6379,172.20.20.2:6380,172.20.20.3:6379,172.20.20.3:6380,172.20.20.4:6379,172.20.20.4:6380 ]
  address: 43.138.111.53:6379
  password: LiuZhiyi20200805
  scan-interval: 8000
  check-slots-coverage: false
  tcp-no-delay: true
  master-connection-minimum-idle-size: 2
  slave-connection-minimum-idle-size: 2
  master-connection-pool-size: 2
  slave-connection-pool-size: 2
  subscription-connection-minimum-idle-size: 2
  subscription-connection-pool-size: 2
  subscriptions-per-connection: 2
  subscription-mode: MASTER
  timeout: 60000
  connect-timeout: 60000
  idle-connection-timeout: 32000
  retry-attempts: 2
  retry-interval: 4000
  keep-alive: true
  dns-monitoring-interval: -1
  ping-connection-interval: 300000
  executor-core-pool-size: 4
  executor-maximum-pool-size: 8
  executor-keep-alive-seconds: 64
  executor-blocking-queue-capacity: 128
  max-tryLock-waiting-millis: 10000


rest:
  max-connections: 64
  worker-count: 64
  use-global-resources: false
  connect-timeout-millis: 7000
  use-tcp-no-delay: false
  protocols: [ HTTP11,H2,H2C ]
  response-timeout-millis: 3000
  read-timeout-millis: 3000
  write-timeout-millis: 3000
  max-byte-in-memory-size: 1048576


dubbo:
  registry:
    id: summer-registry
    client: curator
    protocol: zookeeper
    address: zookeeper://43.138.44.171
    port: 2181
    username: blue
    password: LiuZhiyi20200805
    file: /usr/env/log/dubbo/agreement/registry.properties
    check: false
    timeout: 60000
    simplified: false
#  metadata-report:
#    address: zookeeper://43.138.44.171
#    port: 2181
#    username: blue
#    password: LiuZhiyi20200805
#    timeout: 120000
#    default: true
#    check: false
  protocol:
    name: dubbo
    host: localhost
    port: 60000
    accesslog: /usr/env/log/dubbo/agreement/access.log
  provider:
    retries: 0
    timeout: 10000
    loadbalance: random
  consumer:
    retries: 0
    timeout: 10000
    loadbalance: random
    check: false


debug: false