package temp.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import temp.entity.OptEvent;
import temp.entity.OptEventExample;

public interface OptEventMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    long countByExample(OptEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int deleteByExample(OptEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int insert(OptEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int insertSelective(OptEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    List<OptEvent> selectByExample(OptEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    OptEvent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OptEvent record, @Param("example") OptEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OptEvent record, @Param("example") OptEventExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OptEvent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OptEvent record);
}