package temp.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import temp.entity.SecurityQuestion;
import temp.entity.SecurityQuestionExample;

public interface SecurityQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    long countByExample(SecurityQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int deleteByExample(SecurityQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int insert(SecurityQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int insertSelective(SecurityQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    List<SecurityQuestion> selectByExample(SecurityQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    SecurityQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SecurityQuestion record, @Param("example") SecurityQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SecurityQuestion record, @Param("example") SecurityQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SecurityQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table security_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SecurityQuestion record);
}