DROP DATABASE auth;
DROP DATABASE auth_0;
DROP DATABASE auth_1;

DROP DATABASE media_0;
DROP DATABASE media_1;

DROP DATABASE finance;
DROP DATABASE finance_0;
DROP DATABASE finance_1;

DROP DATABASE marketing;
DROP DATABASE marketing_0;
DROP DATABASE marketing_1;

DROP DATABASE member;
DROP DATABASE member_0;
DROP DATABASE member_1;

DROP DATABASE portal;
DROP DATABASE portal_0;
DROP DATABASE portal_1;

DROP DATABASE article;
DROP DATABASE article_0;
DROP DATABASE article_1;

DROP DATABASE base;
DROP DATABASE base_0;
DROP DATABASE base_1;