package com.blue.rdatabase.api.conf;

import java.util.List;
import java.util.Map;

/**
 * data access params
 *
 * @author liuyunfei
 */
@SuppressWarnings({"AlibabaAbstractMethodOrInterfaceMethodMustUseJavadoc", "unused", "SpellCheckingInspection"})
public abstract class BaseDataAccessConfParams implements DataAccessConf {

    /**
     * database shard
     */
    protected transient List<ShardingDatabaseAttr> shardingDatabases;

    /**
     * tables to be sharding
     */
    protected transient List<ShardingTableAttr> shardingTables;

    /**
     * table sharding size per db
     */
    protected transient Integer shardingTableSizePerDatabase;

    /**
     * data center id to db index mappings
     */
    protected transient List<IdentityToShardingMappingAttr> dataCenterToDatabaseMappings;

    /**
     * worker id to db index mappings
     */
    protected transient List<IdentityToShardingMappingAttr> workerToTableMappings;

    /**
     * force write tables
     */
    protected transient List<ForceWriteTableAttr> forceWriteTables;

    /**
     * broadcast tables, now supply for seata undolog
     */
    protected transient List<String> broadcastTables;

    /**
     * db and tables for not sharding
     */
    protected transient List<SingleDatabaseWithTablesAttr> singleDatabasesWithTables;

    protected Boolean safeRowBoundsEnabled;

    protected Boolean safeResultHandlerEnabled;

    protected Boolean mapUnderscoreToCamelCase;
    /**
     * enable aggress lazy loading
     */
    protected Boolean aggressiveLazyLoading;

    /**
     * enable multi result set
     */
    protected Boolean multipleResultSetsEnabled;

    /**
     * use generated keys, false in summer, all id are generated by snowfalke
     */
    protected Boolean useGeneratedKeys;

    /**
     * use column label
     */
    protected Boolean useColumnLabel;

    /**
     * enable cache
     */
    protected Boolean cacheEnabled;

    protected Boolean callSettersOnNulls;

    protected Boolean useActualParamName;

    protected Boolean returnInstanceForEmptyRow;

    protected Boolean shrinkWhitespacesInSql;

    protected Boolean nullableOnForEach;

    protected Integer defaultStatementTimeout;

    protected Integer defaultFetchSize;

    /**
     * enable lazy loading
     */
    protected Boolean lazyLoadingEnabled;

    /**
     * mybatis mapper location
     */
    protected transient String mapperLocation;

    /**
     * additional attributes
     */
    protected transient Map<String, String> props;

    /**
     * show sql log?
     */
    protected Boolean debugLogging;

    public BaseDataAccessConfParams() {
    }

    @Override
    public List<ShardingDatabaseAttr> getShardingDatabases() {
        return shardingDatabases;
    }

    @Override
    public List<ShardingTableAttr> getShardingTables() {
        return shardingTables;
    }

    @Override
    public Integer getShardingTableSizePerDatabase() {
        return shardingTableSizePerDatabase;
    }

    @Override
    public List<IdentityToShardingMappingAttr> getDataCenterToDatabaseMappings() {
        return dataCenterToDatabaseMappings;
    }

    @Override
    public List<IdentityToShardingMappingAttr> getWorkerToTableMappings() {
        return workerToTableMappings;
    }

    @Override
    public List<ForceWriteTableAttr> getForceWriteTables() {
        return forceWriteTables;
    }

    @Override
    public List<String> getBroadcastTables() {
        return broadcastTables;
    }

    @Override
    public List<SingleDatabaseWithTablesAttr> getSingleDatabasesWithTables() {
        return singleDatabasesWithTables;
    }

    @Override
    public Boolean getSafeRowBoundsEnabled() {
        return safeRowBoundsEnabled;
    }

    @Override
    public Boolean getSafeResultHandlerEnabled() {
        return safeResultHandlerEnabled;
    }

    @Override
    public Boolean getMapUnderscoreToCamelCase() {
        return mapUnderscoreToCamelCase;
    }

    @Override
    public Boolean getAggressiveLazyLoading() {
        return aggressiveLazyLoading;
    }

    @Override
    public Boolean getMultipleResultSetsEnabled() {
        return multipleResultSetsEnabled;
    }

    @Override
    public Boolean getUseGeneratedKeys() {
        return useGeneratedKeys;
    }

    @Override
    public Boolean getUseColumnLabel() {
        return useColumnLabel;
    }

    @Override
    public Boolean getCacheEnabled() {
        return cacheEnabled;
    }

    @Override
    public Boolean getCallSettersOnNulls() {
        return callSettersOnNulls;
    }

    @Override
    public Boolean getUseActualParamName() {
        return useActualParamName;
    }

    @Override
    public Boolean getReturnInstanceForEmptyRow() {
        return returnInstanceForEmptyRow;
    }

    @Override
    public Boolean getShrinkWhitespacesInSql() {
        return shrinkWhitespacesInSql;
    }

    @Override
    public Boolean getNullableOnForEach() {
        return nullableOnForEach;
    }

    @Override
    public Integer getDefaultStatementTimeout() {
        return defaultStatementTimeout;
    }

    @Override
    public Integer getDefaultFetchSize() {
        return defaultFetchSize;
    }

    @Override
    public Boolean getLazyLoadingEnabled() {
        return lazyLoadingEnabled;
    }


    @Override
    public String getMapperLocation() {
        return mapperLocation;
    }

    @Override
    public Map<String, String> getProps() {
        return props;
    }

    @Override
    public Boolean getDebugLogging() {
        return debugLogging;
    }

    public void setShardingDatabases(List<ShardingDatabaseAttr> shardingDatabases) {
        this.shardingDatabases = shardingDatabases;
    }

    public void setShardingTables(List<ShardingTableAttr> shardingTables) {
        this.shardingTables = shardingTables;
    }

    public void setShardingTableSizePerDatabase(Integer shardingTableSizePerDatabase) {
        this.shardingTableSizePerDatabase = shardingTableSizePerDatabase;
    }

    public void setDataCenterToDatabaseMappings(List<IdentityToShardingMappingAttr> dataCenterToDatabaseMappings) {
        this.dataCenterToDatabaseMappings = dataCenterToDatabaseMappings;
    }

    public void setWorkerToTableMappings(List<IdentityToShardingMappingAttr> workerToTableMappings) {
        this.workerToTableMappings = workerToTableMappings;
    }

    public void setForceWriteTables(List<ForceWriteTableAttr> forceWriteTables) {
        this.forceWriteTables = forceWriteTables;
    }

    public void setBroadcastTables(List<String> broadcastTables) {
        this.broadcastTables = broadcastTables;
    }

    public void setSingleDatabasesWithTables(List<SingleDatabaseWithTablesAttr> singleDatabasesWithTables) {
        this.singleDatabasesWithTables = singleDatabasesWithTables;
    }

    public void setSafeRowBoundsEnabled(Boolean safeRowBoundsEnabled) {
        this.safeRowBoundsEnabled = safeRowBoundsEnabled;
    }

    public void setSafeResultHandlerEnabled(Boolean safeResultHandlerEnabled) {
        this.safeResultHandlerEnabled = safeResultHandlerEnabled;
    }

    public void setMapUnderscoreToCamelCase(Boolean mapUnderscoreToCamelCase) {
        this.mapUnderscoreToCamelCase = mapUnderscoreToCamelCase;
    }

    public void setAggressiveLazyLoading(Boolean aggressiveLazyLoading) {
        this.aggressiveLazyLoading = aggressiveLazyLoading;
    }

    public void setMultipleResultSetsEnabled(Boolean multipleResultSetsEnabled) {
        this.multipleResultSetsEnabled = multipleResultSetsEnabled;
    }

    public void setUseGeneratedKeys(Boolean useGeneratedKeys) {
        this.useGeneratedKeys = useGeneratedKeys;
    }

    public void setUseColumnLabel(Boolean useColumnLabel) {
        this.useColumnLabel = useColumnLabel;
    }

    public void setCacheEnabled(Boolean cacheEnabled) {
        this.cacheEnabled = cacheEnabled;
    }

    public void setCallSettersOnNulls(Boolean callSettersOnNulls) {
        this.callSettersOnNulls = callSettersOnNulls;
    }

    public void setUseActualParamName(Boolean useActualParamName) {
        this.useActualParamName = useActualParamName;
    }

    public void setReturnInstanceForEmptyRow(Boolean returnInstanceForEmptyRow) {
        this.returnInstanceForEmptyRow = returnInstanceForEmptyRow;
    }

    public void setShrinkWhitespacesInSql(Boolean shrinkWhitespacesInSql) {
        this.shrinkWhitespacesInSql = shrinkWhitespacesInSql;
    }

    public void setNullableOnForEach(Boolean nullableOnForEach) {
        this.nullableOnForEach = nullableOnForEach;
    }

    public void setDefaultStatementTimeout(Integer defaultStatementTimeout) {
        this.defaultStatementTimeout = defaultStatementTimeout;
    }

    public void setDefaultFetchSize(Integer defaultFetchSize) {
        this.defaultFetchSize = defaultFetchSize;
    }

    public void setLazyLoadingEnabled(Boolean lazyLoadingEnabled) {
        this.lazyLoadingEnabled = lazyLoadingEnabled;
    }

    public void setMapperLocation(String mapperLocation) {
        this.mapperLocation = mapperLocation;
    }

    public void setProps(Map<String, String> props) {
        this.props = props;
    }

    public void setDebugLogging(Boolean debugLogging) {
        this.debugLogging = debugLogging;
    }

    @Override
    public String toString() {
        return "BaseDataAccessConfParams{" +
                "shardingDatabases=" + shardingDatabases +
                ", shardingTables=" + shardingTables +
                ", shardingTableSizePerDatabase=" + shardingTableSizePerDatabase +
                ", dataCenterToDatabaseMappings=" + dataCenterToDatabaseMappings +
                ", workerToTableMappings=" + workerToTableMappings +
                ", forceWriteTables=" + forceWriteTables +
                ", broadcastTables=" + broadcastTables +
                ", singleDatabasesWithTables=" + singleDatabasesWithTables +
                ", safeRowBoundsEnabled=" + safeRowBoundsEnabled +
                ", safeResultHandlerEnabled=" + safeResultHandlerEnabled +
                ", mapUnderscoreToCamelCase=" + mapUnderscoreToCamelCase +
                ", aggressiveLazyLoading=" + aggressiveLazyLoading +
                ", multipleResultSetsEnabled=" + multipleResultSetsEnabled +
                ", useGeneratedKeys=" + useGeneratedKeys +
                ", useColumnLabel=" + useColumnLabel +
                ", cacheEnabled=" + cacheEnabled +
                ", callSettersOnNulls=" + callSettersOnNulls +
                ", useActualParamName=" + useActualParamName +
                ", returnInstanceForEmptyRow=" + returnInstanceForEmptyRow +
                ", shrinkWhitespacesInSql=" + shrinkWhitespacesInSql +
                ", nullableOnForEach=" + nullableOnForEach +
                ", defaultStatementTimeout=" + defaultStatementTimeout +
                ", defaultFetchSize=" + defaultFetchSize +
                ", lazyLoadingEnabled=" + lazyLoadingEnabled +
                ", mapperLocation='" + mapperLocation + '\'' +
                ", props=" + props +
                ", debugLogging=" + debugLogging +
                '}';
    }

}
