package temp.entity;

import java.util.Date;

public class OptEvent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.data_event_type
     *
     * @mbg.generated
     */
    private String dataEventType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.stamp
     *
     * @mbg.generated
     */
    private Date stamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.uri
     *
     * @mbg.generated
     */
    private String uri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.real_uri
     *
     * @mbg.generated
     */
    private String realUri;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.request_body
     *
     * @mbg.generated
     */
    private String requestBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.response_status
     *
     * @mbg.generated
     */
    private Integer responseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.request_id
     *
     * @mbg.generated
     */
    private String requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.metadata
     *
     * @mbg.generated
     */
    private String metadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.jwt
     *
     * @mbg.generated
     */
    private String jwt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.access
     *
     * @mbg.generated
     */
    private String access;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.client_ip
     *
     * @mbg.generated
     */
    private String clientIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.sec_key
     *
     * @mbg.generated
     */
    private String secKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.request_un_decryption
     *
     * @mbg.generated
     */
    private Integer requestUnDecryption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.response_un_encryption
     *
     * @mbg.generated
     */
    private Integer responseUnEncryption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.existence_request_body
     *
     * @mbg.generated
     */
    private Integer existenceRequestBody;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opt_event.existence_response_body
     *
     * @mbg.generated
     */
    private Integer existenceResponseBody;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.id
     *
     * @return the value of opt_event.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.id
     *
     * @param id the value for opt_event.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.data_event_type
     *
     * @return the value of opt_event.data_event_type
     *
     * @mbg.generated
     */
    public String getDataEventType() {
        return dataEventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.data_event_type
     *
     * @param dataEventType the value for opt_event.data_event_type
     *
     * @mbg.generated
     */
    public void setDataEventType(String dataEventType) {
        this.dataEventType = dataEventType == null ? null : dataEventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.stamp
     *
     * @return the value of opt_event.stamp
     *
     * @mbg.generated
     */
    public Date getStamp() {
        return stamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.stamp
     *
     * @param stamp the value for opt_event.stamp
     *
     * @mbg.generated
     */
    public void setStamp(Date stamp) {
        this.stamp = stamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.method
     *
     * @return the value of opt_event.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.method
     *
     * @param method the value for opt_event.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.uri
     *
     * @return the value of opt_event.uri
     *
     * @mbg.generated
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.uri
     *
     * @param uri the value for opt_event.uri
     *
     * @mbg.generated
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.real_uri
     *
     * @return the value of opt_event.real_uri
     *
     * @mbg.generated
     */
    public String getRealUri() {
        return realUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.real_uri
     *
     * @param realUri the value for opt_event.real_uri
     *
     * @mbg.generated
     */
    public void setRealUri(String realUri) {
        this.realUri = realUri == null ? null : realUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.request_body
     *
     * @return the value of opt_event.request_body
     *
     * @mbg.generated
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.request_body
     *
     * @param requestBody the value for opt_event.request_body
     *
     * @mbg.generated
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody == null ? null : requestBody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.response_status
     *
     * @return the value of opt_event.response_status
     *
     * @mbg.generated
     */
    public Integer getResponseStatus() {
        return responseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.response_status
     *
     * @param responseStatus the value for opt_event.response_status
     *
     * @mbg.generated
     */
    public void setResponseStatus(Integer responseStatus) {
        this.responseStatus = responseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.request_id
     *
     * @return the value of opt_event.request_id
     *
     * @mbg.generated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.request_id
     *
     * @param requestId the value for opt_event.request_id
     *
     * @mbg.generated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.metadata
     *
     * @return the value of opt_event.metadata
     *
     * @mbg.generated
     */
    public String getMetadata() {
        return metadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.metadata
     *
     * @param metadata the value for opt_event.metadata
     *
     * @mbg.generated
     */
    public void setMetadata(String metadata) {
        this.metadata = metadata == null ? null : metadata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.jwt
     *
     * @return the value of opt_event.jwt
     *
     * @mbg.generated
     */
    public String getJwt() {
        return jwt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.jwt
     *
     * @param jwt the value for opt_event.jwt
     *
     * @mbg.generated
     */
    public void setJwt(String jwt) {
        this.jwt = jwt == null ? null : jwt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.access
     *
     * @return the value of opt_event.access
     *
     * @mbg.generated
     */
    public String getAccess() {
        return access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.access
     *
     * @param access the value for opt_event.access
     *
     * @mbg.generated
     */
    public void setAccess(String access) {
        this.access = access == null ? null : access.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.client_ip
     *
     * @return the value of opt_event.client_ip
     *
     * @mbg.generated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.client_ip
     *
     * @param clientIp the value for opt_event.client_ip
     *
     * @mbg.generated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.sec_key
     *
     * @return the value of opt_event.sec_key
     *
     * @mbg.generated
     */
    public String getSecKey() {
        return secKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.sec_key
     *
     * @param secKey the value for opt_event.sec_key
     *
     * @mbg.generated
     */
    public void setSecKey(String secKey) {
        this.secKey = secKey == null ? null : secKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.request_un_decryption
     *
     * @return the value of opt_event.request_un_decryption
     *
     * @mbg.generated
     */
    public Integer getRequestUnDecryption() {
        return requestUnDecryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.request_un_decryption
     *
     * @param requestUnDecryption the value for opt_event.request_un_decryption
     *
     * @mbg.generated
     */
    public void setRequestUnDecryption(Integer requestUnDecryption) {
        this.requestUnDecryption = requestUnDecryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.response_un_encryption
     *
     * @return the value of opt_event.response_un_encryption
     *
     * @mbg.generated
     */
    public Integer getResponseUnEncryption() {
        return responseUnEncryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.response_un_encryption
     *
     * @param responseUnEncryption the value for opt_event.response_un_encryption
     *
     * @mbg.generated
     */
    public void setResponseUnEncryption(Integer responseUnEncryption) {
        this.responseUnEncryption = responseUnEncryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.existence_request_body
     *
     * @return the value of opt_event.existence_request_body
     *
     * @mbg.generated
     */
    public Integer getExistenceRequestBody() {
        return existenceRequestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.existence_request_body
     *
     * @param existenceRequestBody the value for opt_event.existence_request_body
     *
     * @mbg.generated
     */
    public void setExistenceRequestBody(Integer existenceRequestBody) {
        this.existenceRequestBody = existenceRequestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opt_event.existence_response_body
     *
     * @return the value of opt_event.existence_response_body
     *
     * @mbg.generated
     */
    public Integer getExistenceResponseBody() {
        return existenceResponseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opt_event.existence_response_body
     *
     * @param existenceResponseBody the value for opt_event.existence_response_body
     *
     * @mbg.generated
     */
    public void setExistenceResponseBody(Integer existenceResponseBody) {
        this.existenceResponseBody = existenceResponseBody;
    }
}