package temp.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OptEventExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public OptEventExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeIsNull() {
            addCriterion("data_event_type is null");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeIsNotNull() {
            addCriterion("data_event_type is not null");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeEqualTo(String value) {
            addCriterion("data_event_type =", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeNotEqualTo(String value) {
            addCriterion("data_event_type <>", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeGreaterThan(String value) {
            addCriterion("data_event_type >", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeGreaterThanOrEqualTo(String value) {
            addCriterion("data_event_type >=", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeLessThan(String value) {
            addCriterion("data_event_type <", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeLessThanOrEqualTo(String value) {
            addCriterion("data_event_type <=", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeLike(String value) {
            addCriterion("data_event_type like", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeNotLike(String value) {
            addCriterion("data_event_type not like", value, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeIn(List<String> values) {
            addCriterion("data_event_type in", values, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeNotIn(List<String> values) {
            addCriterion("data_event_type not in", values, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeBetween(String value1, String value2) {
            addCriterion("data_event_type between", value1, value2, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andDataEventTypeNotBetween(String value1, String value2) {
            addCriterion("data_event_type not between", value1, value2, "dataEventType");
            return (Criteria) this;
        }

        public Criteria andStampIsNull() {
            addCriterion("stamp is null");
            return (Criteria) this;
        }

        public Criteria andStampIsNotNull() {
            addCriterion("stamp is not null");
            return (Criteria) this;
        }

        public Criteria andStampEqualTo(Date value) {
            addCriterion("stamp =", value, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampNotEqualTo(Date value) {
            addCriterion("stamp <>", value, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampGreaterThan(Date value) {
            addCriterion("stamp >", value, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampGreaterThanOrEqualTo(Date value) {
            addCriterion("stamp >=", value, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampLessThan(Date value) {
            addCriterion("stamp <", value, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampLessThanOrEqualTo(Date value) {
            addCriterion("stamp <=", value, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampIn(List<Date> values) {
            addCriterion("stamp in", values, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampNotIn(List<Date> values) {
            addCriterion("stamp not in", values, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampBetween(Date value1, Date value2) {
            addCriterion("stamp between", value1, value2, "stamp");
            return (Criteria) this;
        }

        public Criteria andStampNotBetween(Date value1, Date value2) {
            addCriterion("stamp not between", value1, value2, "stamp");
            return (Criteria) this;
        }

        public Criteria andMethodIsNull() {
            addCriterion("method is null");
            return (Criteria) this;
        }

        public Criteria andMethodIsNotNull() {
            addCriterion("method is not null");
            return (Criteria) this;
        }

        public Criteria andMethodEqualTo(String value) {
            addCriterion("method =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualTo(String value) {
            addCriterion("method <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThan(String value) {
            addCriterion("method >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(String value) {
            addCriterion("method >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThan(String value) {
            addCriterion("method <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualTo(String value) {
            addCriterion("method <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLike(String value) {
            addCriterion("method like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotLike(String value) {
            addCriterion("method not like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodIn(List<String> values) {
            addCriterion("method in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotIn(List<String> values) {
            addCriterion("method not in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodBetween(String value1, String value2) {
            addCriterion("method between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotBetween(String value1, String value2) {
            addCriterion("method not between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andUriIsNull() {
            addCriterion("uri is null");
            return (Criteria) this;
        }

        public Criteria andUriIsNotNull() {
            addCriterion("uri is not null");
            return (Criteria) this;
        }

        public Criteria andUriEqualTo(String value) {
            addCriterion("uri =", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotEqualTo(String value) {
            addCriterion("uri <>", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriGreaterThan(String value) {
            addCriterion("uri >", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriGreaterThanOrEqualTo(String value) {
            addCriterion("uri >=", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriLessThan(String value) {
            addCriterion("uri <", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriLessThanOrEqualTo(String value) {
            addCriterion("uri <=", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriLike(String value) {
            addCriterion("uri like", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotLike(String value) {
            addCriterion("uri not like", value, "uri");
            return (Criteria) this;
        }

        public Criteria andUriIn(List<String> values) {
            addCriterion("uri in", values, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotIn(List<String> values) {
            addCriterion("uri not in", values, "uri");
            return (Criteria) this;
        }

        public Criteria andUriBetween(String value1, String value2) {
            addCriterion("uri between", value1, value2, "uri");
            return (Criteria) this;
        }

        public Criteria andUriNotBetween(String value1, String value2) {
            addCriterion("uri not between", value1, value2, "uri");
            return (Criteria) this;
        }

        public Criteria andRealUriIsNull() {
            addCriterion("real_uri is null");
            return (Criteria) this;
        }

        public Criteria andRealUriIsNotNull() {
            addCriterion("real_uri is not null");
            return (Criteria) this;
        }

        public Criteria andRealUriEqualTo(String value) {
            addCriterion("real_uri =", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriNotEqualTo(String value) {
            addCriterion("real_uri <>", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriGreaterThan(String value) {
            addCriterion("real_uri >", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriGreaterThanOrEqualTo(String value) {
            addCriterion("real_uri >=", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriLessThan(String value) {
            addCriterion("real_uri <", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriLessThanOrEqualTo(String value) {
            addCriterion("real_uri <=", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriLike(String value) {
            addCriterion("real_uri like", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriNotLike(String value) {
            addCriterion("real_uri not like", value, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriIn(List<String> values) {
            addCriterion("real_uri in", values, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriNotIn(List<String> values) {
            addCriterion("real_uri not in", values, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriBetween(String value1, String value2) {
            addCriterion("real_uri between", value1, value2, "realUri");
            return (Criteria) this;
        }

        public Criteria andRealUriNotBetween(String value1, String value2) {
            addCriterion("real_uri not between", value1, value2, "realUri");
            return (Criteria) this;
        }

        public Criteria andRequestBodyIsNull() {
            addCriterion("request_body is null");
            return (Criteria) this;
        }

        public Criteria andRequestBodyIsNotNull() {
            addCriterion("request_body is not null");
            return (Criteria) this;
        }

        public Criteria andRequestBodyEqualTo(String value) {
            addCriterion("request_body =", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyNotEqualTo(String value) {
            addCriterion("request_body <>", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyGreaterThan(String value) {
            addCriterion("request_body >", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyGreaterThanOrEqualTo(String value) {
            addCriterion("request_body >=", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyLessThan(String value) {
            addCriterion("request_body <", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyLessThanOrEqualTo(String value) {
            addCriterion("request_body <=", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyLike(String value) {
            addCriterion("request_body like", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyNotLike(String value) {
            addCriterion("request_body not like", value, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyIn(List<String> values) {
            addCriterion("request_body in", values, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyNotIn(List<String> values) {
            addCriterion("request_body not in", values, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyBetween(String value1, String value2) {
            addCriterion("request_body between", value1, value2, "requestBody");
            return (Criteria) this;
        }

        public Criteria andRequestBodyNotBetween(String value1, String value2) {
            addCriterion("request_body not between", value1, value2, "requestBody");
            return (Criteria) this;
        }

        public Criteria andResponseStatusIsNull() {
            addCriterion("response_status is null");
            return (Criteria) this;
        }

        public Criteria andResponseStatusIsNotNull() {
            addCriterion("response_status is not null");
            return (Criteria) this;
        }

        public Criteria andResponseStatusEqualTo(Integer value) {
            addCriterion("response_status =", value, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusNotEqualTo(Integer value) {
            addCriterion("response_status <>", value, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusGreaterThan(Integer value) {
            addCriterion("response_status >", value, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("response_status >=", value, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusLessThan(Integer value) {
            addCriterion("response_status <", value, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusLessThanOrEqualTo(Integer value) {
            addCriterion("response_status <=", value, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusIn(List<Integer> values) {
            addCriterion("response_status in", values, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusNotIn(List<Integer> values) {
            addCriterion("response_status not in", values, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusBetween(Integer value1, Integer value2) {
            addCriterion("response_status between", value1, value2, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andResponseStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("response_status not between", value1, value2, "responseStatus");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNull() {
            addCriterion("request_id is null");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNotNull() {
            addCriterion("request_id is not null");
            return (Criteria) this;
        }

        public Criteria andRequestIdEqualTo(String value) {
            addCriterion("request_id =", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotEqualTo(String value) {
            addCriterion("request_id <>", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThan(String value) {
            addCriterion("request_id >", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThanOrEqualTo(String value) {
            addCriterion("request_id >=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThan(String value) {
            addCriterion("request_id <", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThanOrEqualTo(String value) {
            addCriterion("request_id <=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLike(String value) {
            addCriterion("request_id like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotLike(String value) {
            addCriterion("request_id not like", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdIn(List<String> values) {
            addCriterion("request_id in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotIn(List<String> values) {
            addCriterion("request_id not in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdBetween(String value1, String value2) {
            addCriterion("request_id between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotBetween(String value1, String value2) {
            addCriterion("request_id not between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andMetadataIsNull() {
            addCriterion("metadata is null");
            return (Criteria) this;
        }

        public Criteria andMetadataIsNotNull() {
            addCriterion("metadata is not null");
            return (Criteria) this;
        }

        public Criteria andMetadataEqualTo(String value) {
            addCriterion("metadata =", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataNotEqualTo(String value) {
            addCriterion("metadata <>", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataGreaterThan(String value) {
            addCriterion("metadata >", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataGreaterThanOrEqualTo(String value) {
            addCriterion("metadata >=", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataLessThan(String value) {
            addCriterion("metadata <", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataLessThanOrEqualTo(String value) {
            addCriterion("metadata <=", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataLike(String value) {
            addCriterion("metadata like", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataNotLike(String value) {
            addCriterion("metadata not like", value, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataIn(List<String> values) {
            addCriterion("metadata in", values, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataNotIn(List<String> values) {
            addCriterion("metadata not in", values, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataBetween(String value1, String value2) {
            addCriterion("metadata between", value1, value2, "metadata");
            return (Criteria) this;
        }

        public Criteria andMetadataNotBetween(String value1, String value2) {
            addCriterion("metadata not between", value1, value2, "metadata");
            return (Criteria) this;
        }

        public Criteria andJwtIsNull() {
            addCriterion("jwt is null");
            return (Criteria) this;
        }

        public Criteria andJwtIsNotNull() {
            addCriterion("jwt is not null");
            return (Criteria) this;
        }

        public Criteria andJwtEqualTo(String value) {
            addCriterion("jwt =", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtNotEqualTo(String value) {
            addCriterion("jwt <>", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtGreaterThan(String value) {
            addCriterion("jwt >", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtGreaterThanOrEqualTo(String value) {
            addCriterion("jwt >=", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtLessThan(String value) {
            addCriterion("jwt <", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtLessThanOrEqualTo(String value) {
            addCriterion("jwt <=", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtLike(String value) {
            addCriterion("jwt like", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtNotLike(String value) {
            addCriterion("jwt not like", value, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtIn(List<String> values) {
            addCriterion("jwt in", values, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtNotIn(List<String> values) {
            addCriterion("jwt not in", values, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtBetween(String value1, String value2) {
            addCriterion("jwt between", value1, value2, "jwt");
            return (Criteria) this;
        }

        public Criteria andJwtNotBetween(String value1, String value2) {
            addCriterion("jwt not between", value1, value2, "jwt");
            return (Criteria) this;
        }

        public Criteria andAccessIsNull() {
            addCriterion("access is null");
            return (Criteria) this;
        }

        public Criteria andAccessIsNotNull() {
            addCriterion("access is not null");
            return (Criteria) this;
        }

        public Criteria andAccessEqualTo(String value) {
            addCriterion("access =", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotEqualTo(String value) {
            addCriterion("access <>", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessGreaterThan(String value) {
            addCriterion("access >", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessGreaterThanOrEqualTo(String value) {
            addCriterion("access >=", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessLessThan(String value) {
            addCriterion("access <", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessLessThanOrEqualTo(String value) {
            addCriterion("access <=", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessLike(String value) {
            addCriterion("access like", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotLike(String value) {
            addCriterion("access not like", value, "access");
            return (Criteria) this;
        }

        public Criteria andAccessIn(List<String> values) {
            addCriterion("access in", values, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotIn(List<String> values) {
            addCriterion("access not in", values, "access");
            return (Criteria) this;
        }

        public Criteria andAccessBetween(String value1, String value2) {
            addCriterion("access between", value1, value2, "access");
            return (Criteria) this;
        }

        public Criteria andAccessNotBetween(String value1, String value2) {
            addCriterion("access not between", value1, value2, "access");
            return (Criteria) this;
        }

        public Criteria andClientIpIsNull() {
            addCriterion("client_ip is null");
            return (Criteria) this;
        }

        public Criteria andClientIpIsNotNull() {
            addCriterion("client_ip is not null");
            return (Criteria) this;
        }

        public Criteria andClientIpEqualTo(String value) {
            addCriterion("client_ip =", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotEqualTo(String value) {
            addCriterion("client_ip <>", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpGreaterThan(String value) {
            addCriterion("client_ip >", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpGreaterThanOrEqualTo(String value) {
            addCriterion("client_ip >=", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLessThan(String value) {
            addCriterion("client_ip <", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLessThanOrEqualTo(String value) {
            addCriterion("client_ip <=", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLike(String value) {
            addCriterion("client_ip like", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotLike(String value) {
            addCriterion("client_ip not like", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpIn(List<String> values) {
            addCriterion("client_ip in", values, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotIn(List<String> values) {
            addCriterion("client_ip not in", values, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpBetween(String value1, String value2) {
            addCriterion("client_ip between", value1, value2, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotBetween(String value1, String value2) {
            addCriterion("client_ip not between", value1, value2, "clientIp");
            return (Criteria) this;
        }

        public Criteria andSecKeyIsNull() {
            addCriterion("sec_key is null");
            return (Criteria) this;
        }

        public Criteria andSecKeyIsNotNull() {
            addCriterion("sec_key is not null");
            return (Criteria) this;
        }

        public Criteria andSecKeyEqualTo(String value) {
            addCriterion("sec_key =", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyNotEqualTo(String value) {
            addCriterion("sec_key <>", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyGreaterThan(String value) {
            addCriterion("sec_key >", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyGreaterThanOrEqualTo(String value) {
            addCriterion("sec_key >=", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyLessThan(String value) {
            addCriterion("sec_key <", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyLessThanOrEqualTo(String value) {
            addCriterion("sec_key <=", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyLike(String value) {
            addCriterion("sec_key like", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyNotLike(String value) {
            addCriterion("sec_key not like", value, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyIn(List<String> values) {
            addCriterion("sec_key in", values, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyNotIn(List<String> values) {
            addCriterion("sec_key not in", values, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyBetween(String value1, String value2) {
            addCriterion("sec_key between", value1, value2, "secKey");
            return (Criteria) this;
        }

        public Criteria andSecKeyNotBetween(String value1, String value2) {
            addCriterion("sec_key not between", value1, value2, "secKey");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionIsNull() {
            addCriterion("request_un_decryption is null");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionIsNotNull() {
            addCriterion("request_un_decryption is not null");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionEqualTo(Integer value) {
            addCriterion("request_un_decryption =", value, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionNotEqualTo(Integer value) {
            addCriterion("request_un_decryption <>", value, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionGreaterThan(Integer value) {
            addCriterion("request_un_decryption >", value, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionGreaterThanOrEqualTo(Integer value) {
            addCriterion("request_un_decryption >=", value, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionLessThan(Integer value) {
            addCriterion("request_un_decryption <", value, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionLessThanOrEqualTo(Integer value) {
            addCriterion("request_un_decryption <=", value, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionIn(List<Integer> values) {
            addCriterion("request_un_decryption in", values, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionNotIn(List<Integer> values) {
            addCriterion("request_un_decryption not in", values, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionBetween(Integer value1, Integer value2) {
            addCriterion("request_un_decryption between", value1, value2, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andRequestUnDecryptionNotBetween(Integer value1, Integer value2) {
            addCriterion("request_un_decryption not between", value1, value2, "requestUnDecryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionIsNull() {
            addCriterion("response_un_encryption is null");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionIsNotNull() {
            addCriterion("response_un_encryption is not null");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionEqualTo(Integer value) {
            addCriterion("response_un_encryption =", value, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionNotEqualTo(Integer value) {
            addCriterion("response_un_encryption <>", value, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionGreaterThan(Integer value) {
            addCriterion("response_un_encryption >", value, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionGreaterThanOrEqualTo(Integer value) {
            addCriterion("response_un_encryption >=", value, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionLessThan(Integer value) {
            addCriterion("response_un_encryption <", value, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionLessThanOrEqualTo(Integer value) {
            addCriterion("response_un_encryption <=", value, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionIn(List<Integer> values) {
            addCriterion("response_un_encryption in", values, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionNotIn(List<Integer> values) {
            addCriterion("response_un_encryption not in", values, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionBetween(Integer value1, Integer value2) {
            addCriterion("response_un_encryption between", value1, value2, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andResponseUnEncryptionNotBetween(Integer value1, Integer value2) {
            addCriterion("response_un_encryption not between", value1, value2, "responseUnEncryption");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyIsNull() {
            addCriterion("existence_request_body is null");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyIsNotNull() {
            addCriterion("existence_request_body is not null");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyEqualTo(Integer value) {
            addCriterion("existence_request_body =", value, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyNotEqualTo(Integer value) {
            addCriterion("existence_request_body <>", value, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyGreaterThan(Integer value) {
            addCriterion("existence_request_body >", value, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyGreaterThanOrEqualTo(Integer value) {
            addCriterion("existence_request_body >=", value, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyLessThan(Integer value) {
            addCriterion("existence_request_body <", value, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyLessThanOrEqualTo(Integer value) {
            addCriterion("existence_request_body <=", value, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyIn(List<Integer> values) {
            addCriterion("existence_request_body in", values, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyNotIn(List<Integer> values) {
            addCriterion("existence_request_body not in", values, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyBetween(Integer value1, Integer value2) {
            addCriterion("existence_request_body between", value1, value2, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceRequestBodyNotBetween(Integer value1, Integer value2) {
            addCriterion("existence_request_body not between", value1, value2, "existenceRequestBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyIsNull() {
            addCriterion("existence_response_body is null");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyIsNotNull() {
            addCriterion("existence_response_body is not null");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyEqualTo(Integer value) {
            addCriterion("existence_response_body =", value, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyNotEqualTo(Integer value) {
            addCriterion("existence_response_body <>", value, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyGreaterThan(Integer value) {
            addCriterion("existence_response_body >", value, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyGreaterThanOrEqualTo(Integer value) {
            addCriterion("existence_response_body >=", value, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyLessThan(Integer value) {
            addCriterion("existence_response_body <", value, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyLessThanOrEqualTo(Integer value) {
            addCriterion("existence_response_body <=", value, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyIn(List<Integer> values) {
            addCriterion("existence_response_body in", values, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyNotIn(List<Integer> values) {
            addCriterion("existence_response_body not in", values, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyBetween(Integer value1, Integer value2) {
            addCriterion("existence_response_body between", value1, value2, "existenceResponseBody");
            return (Criteria) this;
        }

        public Criteria andExistenceResponseBodyNotBetween(Integer value1, Integer value2) {
            addCriterion("existence_response_body not between", value1, value2, "existenceResponseBody");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table opt_event
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table opt_event
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}